### ISSUE TITLE
Can distill.js be used on other non-distill web pages? 

### ISSUE THREAD

**Issue by adnan-wahab** [distillpub/template#13]
Can we use the same distill.js file to add citations, appendices, footnotes, layout and syntax highlighting to articles that are not for distill.pub? 

I want to create some articles for distil, but wanted to mirror them at my website and also have them look consistent with other articles on other topics. (I think the same visual explanation style would be very cool for physics, for example). 

I was in the middle of writing my own set of styles for this purpose, heavily inspired by https://www.gwern.net/Spaced%20repetition

but it looks like the distill.js library is much more complete than my pile of hacks and I'd like to replace it if that's ok.

**Comment by rowanc1** [comment]
It would be really awesome to see a license file in the repository! 

This looks like a pretty great and simple scientific publishing tool (at least the styles), that could have reuse across other scientific domains. 

We are currently pulling our scientific work together in a `python + sphinx_docs + html_hacking` "style", in **electromagnetic geophysics**. I could see immediate reuse of the styles and tags you have created in our various textbook like resources in http://geosci.xyz.

For example: http://em.geosci.xyz/content/maxwell2_static/fields_from_grounded_sources_dcr/electrostatic_sphere.html

cc @lheagy

**Comment by shancarter** [comment]
Our goal is to try to provide a good license for those looking to use these tools on websites other than distill.pub. We're still working out the specifics however, sorry. I will post back when we have a better answer for you.

**Comment by kedartatwawadi** [comment]
Thanks Distill team for providing the very useful template! It would be great if these templates can be used for more broad fields apart from ML which the journal aims for. 

I found some issues using the template while hosting on [github pages](https://kedartatwawadi.github.io/post--ANS/), as the template was not being used. I believe this is because Github Pages by default [uses HTTPS](https://stackoverflow.com/questions/38852819/javascript-wont-run-on-github-pages-site), while the Distill template does not. 
I tried changing the line below to HTTPS, but it does not seem to work)
```javascript
<script src="http://distill.pub/template.v1.js"></script>
```

Currently, I have just copied the template locally, but I believe it would be great to use the hosted link directly to make use of any future improvements/changes. Is there a better way to do this, or am I missing anything?

**Comment by shancarter** [comment]
You can't include http scripts on https pages, sorry.

**Comment by pbamotra** [comment]
Any updates on the license @authors?

**Comment by shancarter** [comment]
No updates on license or contributors, sorry, but we have upgraded to https.
