### ISSUE TITLE
Illegal constructor on Firefox

### ISSUE THREAD

**Issue by humbertaco** [distillpub/template#85]
The template throws an Illegal Constructor Exception on Firefox (tested on version 61.0.1 (64-bit) Ubuntu). The error seems to be due to Custom Elements, more specifically the file src/mixins/template.js. When it tries to call super(), the error is thrown.

**Comment by ludwigschubert** [comment]
You're correct, but unfortunately this "Works As Intended", in the sense that our rendering process during publication adds polyfills for browsers that require them. (And we, sadly, don't support article development in browsers without Custom Element support.)

We're re-considering our move to Custom Elements. Since version 3 of this template may not need Custom Element support, we're not currently investing into a solution for this problem.
